name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via Bastion
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASTION }}" > ~/.ssh/bastion_key
          echo "${{ secrets.SSH_PRIVATE_KEY_PRIVATE }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/bastion_key
          chmod 600 ~/.ssh/private_key

          cat >> ~/.ssh/config <<EOF
          Host bastion
            HostName ${{ secrets.BASTION_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/bastion_key
            StrictHostKeyChecking no

          Host private
            HostName ${{ secrets.IP_ec2_front }}
            User ubuntu
            IdentityFile ~/.ssh/private_key
            ProxyJump bastion
            StrictHostKeyChecking no
          EOF
          
          ssh private << 'ENDSSH'
            set -e
          
            cd /home/ubuntu/match-IQ-front
          
            echo "Actualizando repositorio..."
            git pull origin main
          
            echo "Instalando dependencias..."
            /home/ubuntu/flutter/bin/flutter pub get
          
            echo "Compilando Flutter Web..."
            /home/ubuntu/flutter/bin/flutter build web
          
            echo "Reiniciando servicio..."
            sudo systemctl restart flutter-web
          
            echo "Despliegue completado."
          ENDSSH
